CREATE TABLE Homework (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(256) NOT NULL,
DESCRIPTION VARCHAR(256) NOT NULL
);


CREATE TABLE Lesson (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(256) NOT NULL,
updatedAt TIME NOT NULL
);
ALTER TABLE Lesson
    ADD homework_id INT;

alter table Lesson
    ADD foreign key (homework_id )  REFERENCES homework(ID);
